services:
  postgres:
    image: postgres:17
    container_name: ofeel-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ofeel
      POSTGRES_PASSWORD: ofeel_dev
      POSTGRES_DB: ofeel

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
